"""Normalización de ingredientes detectados / del recetario.

El matching de sinónimos es multilingüe (español / inglés / francés) y usa
límites de palabra, con prioridad al alias más largo primero.
"""

import re
import unicodedata

# Sinónimos → forma canónica panameña (singular, sin acento al final).
SYNONYMS: dict[str, str] = {
    # ---- Español / regional panameño ----
    "aji": "ají",
    "ají": "ají",
    "ajies": "ají",
    "ajíes": "ají",
    "aji dulce": "ají dulce",
    "ají dulce": "ají dulce",
    "ajo": "ajo",
    "ajo en polvo": "ajo",
    "diente de ajo": "diente de ajo",
    "cebolla": "cebolla",
    "cebolla cabezona": "cebolla",
    "cebolla blanca": "cebolla",
    "cebolla roja": "cebolla",
    "chiltoma": "tomate",
    "tomate": "tomate",
    "tomate chonto": "tomate",
    "tomate perita": "tomate",
    "tomate cherry": "tomate cherry",
    "tomates cherry": "tomate cherry",
    "cebollín": "cebollín",
    "cebollin": "cebollín",
    "cebolleta": "cebollín",
    "cebolletas": "cebollín",
    "cebolla larga": "cebollín",
    "culantro": "culantro",
    "cilantro": "culantro",
    "recado": "sazón",
    "sazonador": "sazón",
    "condimento": "sazón",
    "sazon": "sazón",
    "comino": "comino",
    "orégano": "orégano",
    "oregano": "orégano",
    "laurel": "laurel",
    "tomillo": "tomillo",
    "albahaca": "albahaca",
    "pimienta": "pimienta",
    "pimienta negra": "pimienta",
    "la pimienta": "pimienta",
    "sal": "sal",
    "pimiento": "pimiento",
    "pimientos": "pimiento",
    "pimenton": "pimiento",
    "pimentón": "pimiento",
    "pimiento morron": "pimiento",
    "ajicito": "ají",
    "chile": "ají",
    "chiles": "ají",
    "mantequilla": "mantequilla",
    "margarina": "mantequilla",
    "aceite": "aceite",
    "aceite vegetal": "aceite",
    "aceite de girasol": "aceite",
    "aceite de oliva": "aceite de oliva",
    "aceite de maíz": "aceite",
    "aceite de canola": "aceite",
    "guandu": "guandú",
    "guandules": "guandú",
    "guandul": "guandú",
    "frijol": "frijol",
    "frijoles": "frijol",
    "habichuela": "frijol",
    "habichuelas": "frijol",
    "habas": "habas",
    "arveja": "arveja",
    "arvejas": "arveja",
    "guisante": "arveja",
    "guisantes": "arveja",
    "platano": "plátano",
    "platanos": "plátano",
    "plátano": "plátano",
    "plátano maduro": "plátano maduro",
    "plátano verde": "plátano verde",
    "banano": "banano",
    "bananos": "banano",
    "banana": "banano",
    "bananas": "banano",
    "guineo": "banano",
    "patacones": "plátano",
    "patacon": "plátano",
    "yucca": "yuca",
    "yuca": "yuca",
    "ñame": "ñame",
    "papa": "papa",
    "papas": "papa",
    "camote": "boniato",
    "batata": "boniato",
    "boniato": "boniato",
    "camaron": "camarón",
    "camarones": "camarón",
    "pescado": "pescado",
    "corvina": "pescado",
    "tilapia": "pescado",
    "pollo": "pollo",
    "gallina": "pollo",
    "pechuga": "pechuga de pollo",
    "pechuga de pollo": "pechuga de pollo",
    "pollo molido": "pollo molido",
    "carne": "carne",
    "carne de res": "carne",
    "carne molida": "carne",
    "res": "carne",
    "bistec": "carne",
    "cortes de res": "carne",
    "carne de cerdo": "cerdo",
    "chancho": "cerdo",
    "cerdo": "cerdo",
    "puerco": "cerdo",
    "lomo": "cerdo",
    "tocino": "tocino",
    "salchicha": "salchicha",
    "salchichas": "salchicha",
    "chorizo": "chorizo",
    "jamón": "jamón",
    "jamon": "jamón",
    "chicharrón": "chicharrón",
    "pescado seco": "pescado",
    "huevos": "huevo",
    "huevo de gallina": "huevo",
    "yema": "yema",
    "clara": "clara",
    "arroz": "arroz",
    "arroz blanco": "arroz",
    "arroz amarillo": "arroz",
    "azucar": "azúcar",
    "azúcar": "azúcar",
    "azucar blanca": "azúcar",
    "azúcar morena": "azúcar morena",
    "dulce": "dulce",
    "leche": "leche",
    "leche entera": "leche",
    "leche evaporada": "leche evaporada",
    "leche condensada": "leche condensada",
    "leche en polvo": "leche en polvo",
    "klim": "leche en polvo",
    "klim en polvo": "leche en polvo",
    "crema": "crema",
    "crema de leche": "crema de leche",
    "crema de mesa": "crema de leche",
    "harina": "harina",
    "harina de trigo": "harina",
    "harina de maiz": "harina de maíz",
    "harina de maíz": "harina de maíz",
    "harina precocida": "harina de maíz",
    "maicena": "maicena",
    "maiz": "maíz",
    "maíz": "maíz",
    "maiz tierno": "maíz tierno",
    "maíz tierno": "maíz tierno",
    "maiz dulce": "maíz dulce",
    "elote": "maíz tierno",
    "mazorca": "mazorca",
    "levadura": "levadura",
    "polvo de hornear": "polvo de hornear",
    "royal": "polvo de hornear",
    "bicarbonato": "bicarbonato",
    "zapallo": "zapallo",
    "auyama": "zapallo",
    "calabaza": "zapallo",
    "calabacín": "zapallo",
    "zanahoria": "zanahoria",
    "zanahorias": "zanahoria",
    "apio": "apio",
    "repollo": "repollo",
    "col": "repollo",
    "lechuga": "lechuga",
    "pepino": "pepino",
    "espinaca": "espinaca",
    "brocoli": "brócoli",
    "brócoli": "brócoli",
    "molondron": "molondrón",
    "molondrón": "molondrón",
    "coco": "coco",
    "leche de coco": "leche de coco",
    "coco rallado": "coco",
    "miel": "miel",
    "vainilla": "vainilla",
    "esencia de vainilla": "vainilla",
    "extracto de vainilla": "vainilla",
    "canela": "canela",
    "canela en polvo": "canela",
    "canela en raja": "canela en raja",
    "nuez moscada": "nuez moscada",
    "nuez": "nuez",
    "nueces": "nuez",
    "chocolate": "chocolate",
    "cacao": "chocolate",
    "dulce de leche": "dulce de leche",
    "arequipe": "dulce de leche",
    "maní": "maní",
    "mani": "maní",
    "ajonjolí": "ajonjolí",
    "gelatina": "gelatina",
    "paquete de gelatina": "gelatina",
    "hielo": "hielo",
    "hielo triturado": "hielo",
    "avena": "avena",
    "hojuelas de avena": "avena",
    "limón": "limón",
    "limon": "limón",
    "lima": "limón",
    "naranja": "naranja",
    "mandarina": "naranja",
    "mango": "mango",
    "piña": "piña",
    "fresa": "fresa",
    "fresas": "fresa",
    "sandia": "sandía",
    "sandía": "sandía",
    "maracuya": "maracuyá",
    "maracuyá": "maracuyá",
    "aguacate": "aguacate",
    "tomate de árbol": "tomate",
    "champinones": "champiñones",
    "champiñones": "champiñones",
    "hongos": "champiñones",
    "mantequilla de maní": "mantequilla de maní",
    "vinagre": "vinagre",
    "caldo": "caldo",
    "caldo de pollo": "caldo de pollo",
    "caldo de res": "caldo de res",
    "caldo de verduras": "caldo de verduras",
    "salsa de tomate": "salsa de tomate",
    "pastas": "pasta",
    "pasta": "pasta",
    "fideo": "fideo",
    "fideos": "fideo",
    "espagueti": "pasta",
    "espaguetis": "pasta",
    "pan": "pan",
    "pan duro": "pan",
    "pan dulce": "pan",
    "torta": "torta",
    "bizcocho": "bizcocho",
    "galleta": "galleta",
    "galletas": "galleta",
    "galletas maria": "galletas maría",
    "galletas maría": "galletas maría",
    "tortilla": "tortilla",
    "tortilla de maiz": "tortilla de maíz",
    "tortilla de maíz": "tortilla de maíz",
    "masa": "masa",
    "masa de maiz": "masa de maíz",
    "masa de maíz": "masa de maíz",
    "hojaldra": "hojaldra",
    "hojaldre": "hojaldra",
    "pascual hojaldras": "hojaldra",
    "pasas": "pasas",
    "pasitas": "pasas",
    "aceituna": "aceituna",
    "aceitunas": "aceituna",
    "alcaparra": "alcaparra",
    "alcaparras": "alcaparra",
    "yaroa": "yaroa",
    # ---- English ----
    "chicken": "pollo",
    "chicken breast": "pechuga de pollo",
    "chicken breast fillets": "pechuga de pollo",
    "chicken thighs": "pollo",
    "chicken drumsticks": "patitas de pollo",
    "hen": "pollo",
    "rice": "arroz",
    "white rice": "arroz",
    "long grain rice": "arroz",
    "corn": "maíz",
    "sweet corn": "maíz dulce",
    "corn kernels": "maíz tierno",
    "corn on the cob": "mazorca",
    "cornmeal": "harina de maíz",
    "corn flour": "harina de maíz",
    "precooked cornmeal": "harina de maíz",
    "corn starch": "maicena",
    "cornstarch": "maicena",
    "beans": "frijol",
    "bean": "frijol",
    "black beans": "frijol",
    "red beans": "frijol",
    "kidney beans": "frijol",
    "refried beans": "frijol",
    "lentils": "lentejas",
    "potato": "papa",
    "potatoes": "papa",
    "sweet potato": "boniato",
    "sweet potatoes": "boniato",
    "mashed potatoes": "puré de papas",
    "onion": "cebolla",
    "onions": "cebolla",
    "red onion": "cebolla",
    "yellow onion": "cebolla",
    "green onion": "cebollín",
    "green onions": "cebollín",
    "scallion": "cebollín",
    "scallions": "cebollín",
    "garlic": "ajo",
    "garlic cloves": "diente de ajo",
    "garlic clove": "diente de ajo",
    "tomato": "tomate",
    "tomatoes": "tomate",
    "cherry tomatoes": "tomate cherry",
    "tomato paste": "salsa de tomate",
    "tomato sauce": "salsa de tomate",
    "bell pepper": "pimiento",
    "bell peppers": "pimiento",
    "peppers": "pimiento",
    "capsicum": "pimiento",
    "cheese": "queso",
    "american cheese": "queso americano",
    "mozzarella": "queso",
    "cheddar": "queso",
    "grated cheese": "queso",
    "milk": "leche",
    "whole milk": "leche",
    "evaporated milk": "leche evaporada",
    "condensed milk": "leche condensada",
    "sweetened condensed milk": "leche condensada",
    "powdered milk": "leche en polvo",
    "milk powder": "leche en polvo",
    "egg": "huevo",
    "eggs": "huevo",
    "egg yolk": "yema",
    "egg whites": "clara",
    "egg white": "clara",
    "flour": "harina",
    "wheat flour": "harina",
    "all purpose flour": "harina",
    "sugar": "azúcar",
    "brown sugar": "azúcar morena",
    "beef": "carne",
    "ground beef": "carne",
    "steak": "carne",
    "beef steak": "carne",
    "beef broth": "caldo de res",
    "beef stock": "caldo de res",
    "pork": "cerdo",
    "ground pork": "cerdo",
    "pork rind": "chicharrón",
    "bacon": "tocino",
    "sausage": "salchicha",
    "sausages": "salchicha",
    "ham": "jamón",
    "fish": "pescado",
    "shrimp": "camarón",
    "shrimps": "camarón",
    "prawns": "camarón",
    "crab": "cangrejo",
    "plantain": "plátano",
    "plantains": "plátano",
    "green plantain": "plátano verde",
    "ripe plantain": "plátano maduro",
    "yam": "ñame",
    "cassava": "yuca",
    "butter": "mantequilla",
    "unsalted butter": "mantequilla",
    "margarine": "mantequilla",
    "oil": "aceite",
    "cooking oil": "aceite",
    "vegetable oil": "aceite",
    "olive oil": "aceite de oliva",
    "salt": "sal",
    "table salt": "sal",
    "pepper": "pimienta",
    "black pepper": "pimienta",
    "white pepper": "pimienta",
    "cream": "crema",
    "heavy cream": "crema de leche",
    "whipping cream": "crema de leche",
    "oats": "avena",
    "oat": "avena",
    "oatmeal": "avena",
    "rolled oats": "avena",
    "honey": "miel",
    "vanilla": "vainilla",
    "vanilla extract": "vainilla",
    "cinnamon": "canela",
    "ground cinnamon": "canela",
    "cinnamon stick": "canela en raja",
    "nutmeg": "nuez moscada",
    "coriander": "culantro",
    "avocado": "aguacate",
    "lemon": "limón",
    "lime": "limón",
    "mandarin": "naranja",
    "strawberry": "fresa",
    "strawberries": "fresa",
    "passion fruit": "maracuyá",
    "pineapple": "piña",
    "watermelon": "sandía",
    "pumpkin": "zapallo",
    "squash": "zapallo",
    "cabbage": "repollo",
    "carrot": "zanahoria",
    "carrots": "zanahoria",
    "celery": "apio",
    "spinach": "espinaca",
    "lettuce": "lechuga",
    "cucumber": "pepino",
    "broccoli": "brócoli",
    "grilled cheese": "queso",
    "melted cheese": "queso",
    "gelatin": "gelatina",
    "jello": "gelatina",
    "ice": "hielo",
    "crushed ice": "hielo",
    "chicken broth": "caldo de pollo",
    "broth": "caldo",
    "stock": "caldo",
    "yeast": "levadura",
    "baking powder": "polvo de hornear",
    "baking soda": "bicarbonato",
    "dough": "masa",
    "corn tortilla": "tortilla de maíz",
    "tortillas": "tortilla",
    "bread": "pan",
    "hard bread": "pan",
    "sweet bread": "pan dulce",
    "cake": "bizcocho",
    "sponge cake": "bizcocho",
    "maria cookies": "galletas maría",
    # ---- Français ----
    "poulet": "pollo",
    "blanc de poulet": "pechuga de pollo",
    "cuisses de poulet": "pollo",
    "pilons de poulet": "patitas de pollo",
    "poule": "pollo",
    "riz": "arroz",
    "riz blanc": "arroz",
    "riz long grain": "arroz",
    "maïs": "maíz",
    "mais": "maíz",
    "maïs doux": "maíz dulce",
    "épis de maïs": "mazorca",
    "farine de maïs": "harina de maíz",
    "fécule de maïs": "maicena",
    "fecule de mais": "maicena",
    "haricots": "frijol",
    "haricot": "frijol",
    "haricots rouges": "frijol",
    "haricots noirs": "frijol",
    "lentilles": "lentejas",
    "pomme de terre": "papa",
    "pommes de terre": "papa",
    "patate": "papa",
    "patates": "papa",
    "purée de pommes de terre": "puré de papas",
    "patate douce": "boniato",
    "oignon": "cebolla",
    "oignons": "cebolla",
    "oignon rouge": "cebolla",
    "cébette": "cebollín",
    "cebette": "cebollín",
    "ciboulette": "cebollín",
    "ail": "ajo",
    "gousse d'ail": "diente de ajo",
    "gousses d'ail": "diente de ajo",
    "tomates": "tomate",
    "tomates cerises": "tomate cherry",
    "concentré de tomate": "salsa de tomate",
    "sauce tomate": "salsa de tomate",
    "poivron": "pimiento",
    "poivrons": "pimiento",
    "piment": "ají",
    "fromage": "queso",
    "fromage râpé": "queso",
    "fromage râpe": "queso",
    "lait": "leche",
    "lait entier": "leche",
    "lait évaporé": "leche evaporada",
    "lait évapore": "leche evaporada",
    "lait concentré": "leche condensada",
    "lait concentre": "leche condensada",
    "lait en poudre": "leche en polvo",
    "oeuf": "huevo",
    "oeufs": "huevo",
    "œuf": "huevo",
    "œufs": "huevo",
    "jaune d'oeuf": "yema",
    "blanc d'oeuf": "clara",
    "farine": "harina",
    "farine de blé": "harina",
    "farine de ble": "harina",
    "sucre": "azúcar",
    "sucre roux": "azúcar morena",
    "boeuf": "carne",
    "bœuf": "carne",
    "viande hachée": "carne",
    "viande hachee": "carne",
    "bouillon de boeuf": "caldo de res",
    "porc": "cerdo",
    "cochon": "cerdo",
    "lard": "tocino",
    "saucisse": "salchicha",
    "saucisses": "salchicha",
    "jambon": "jamón",
    "poisson": "pescado",
    "crevette": "camarón",
    "crevettes": "camarón",
    "banane": "banano",
    "bananes": "banano",
    "banane verte": "plátano verde",
    "igname": "ñame",
    "manioc": "yuca",
    "beurre": "mantequilla",
    "huile": "aceite",
    "huile végétale": "aceite",
    "huile vegetale": "aceite",
    "huile d'olive": "aceite de oliva",
    "huile de tournesol": "aceite",
    "sel": "sal",
    "poivre": "pimienta",
    "poivre noir": "pimienta",
    "crème": "crema",
    "crème liquide": "crema de leche",
    "crème entière": "crema de leche",
    "crème entiere": "crema de leche",
    "avoine": "avena",
    "flocons d'avoine": "avena",
    "vanille": "vainilla",
    "extrait de vanille": "vainilla",
    "cannelle": "canela",
    "noix de muscade": "nuez moscada",
    "coriandre": "culantro",
    "avocat": "aguacate",
    "citron": "limón",
    "citron vert": "limón",
    "mandarine": "naranja",
    "mangue": "mango",
    "fraise": "fresa",
    "fraises": "fresa",
    "fruit de la passion": "maracuyá",
    "maracuja": "maracuyá",
    "ananas": "piña",
    "pastèque": "sandía",
    "pasteque": "sandía",
    "potiron": "zapallo",
    "citrouille": "zapallo",
    "chou": "repollo",
    "choux": "repollo",
    "carotte": "zanahoria",
    "carottes": "zanahoria",
    "céleri": "apio",
    "celeri": "apio",
    "épinard": "espinaca",
    "epinard": "espinaca",
    "laitue": "lechuga",
    "concombre": "pepino",
    "gélatine": "gelatina",
    "gelatine": "gelatina",
    "glace": "hielo",
    "glace pilée": "hielo",
    "levure": "levadura",
    "levure chimique": "polvo de hornear",
    "bicarbonate de soude": "bicarbonato",
    "pâte": "masa",
    "noix": "nuez",
    "chocolat": "chocolate",
    "yaourt": "yogur",
    "crème glacée": "helado",
    "crème glacee": "helado",
}

# Términos que se descartan al detectar (no son ingredientes reales).
STOPWORDS = {
    "al gusto",
    "sal al gusto",
    "pimienta al gusto",
    "agua",
    "un poco de agua",
    "aceite para freír",
    "aceite para cocinar",
    "un poco de aceite para cocinar",
}

_BRACKET_RE = re.compile(r"\(.*?\)")

_SORTED_ALIASES = tuple(sorted(SYNONYMS, key=len, reverse=True))


def strip_accents(text: str) -> str:
    normalized = unicodedata.normalize("NFD", text)
    return "".join(c for c in normalized if unicodedata.category(c) != "Mn")


def _word_has_alias(alias: str, text: str) -> bool:
    """¿El texto contiene el alias como palabra completa (límites unicode)?"""
    pattern = r"(?<![^\W_])" + re.escape(alias) + r"(?![^\W_])"
    return re.search(pattern, text) is not None


def _apply_synonyms(text: str) -> str:
    if text in SYNONYMS:
        return SYNONYMS[text]
    for alias in _SORTED_ALIASES:
        if _word_has_alias(alias, text):
            return SYNONYMS[alias]
    return text


def normalize_ingredient(raw: str) -> str:
    """Lleva un ingrediente a una forma canónica para matching."""
    text = raw.lower().strip()
    text = _BRACKET_RE.sub("", text).strip()
    text = re.sub(r"\s+", " ", text)
    if text in STOPWORDS:
        return ""
    text = re.sub(r"(?:es|s)\.?$", "", text)  # plural/singular (aplicar antes de sinónimos)

    text = _apply_synonyms(text)

    text = re.sub(r"\s+", " ", text).strip()
    if text in STOPWORDS:
        return ""
    return strip_accents(text)


def normalize_list(names: list[str]) -> list[str]:
    """Normaliza una lista y descarta vacíos/stopwords, sin duplicados."""
    seen: set[str] = set()
    result: list[str] = []
    for name in names:
        norm = normalize_ingredient(name)
        if norm and norm not in seen:
            seen.add(norm)
            result.append(norm)
    return result


def synonym_aliases_for(canonical: str) -> list[str]:
    """Todos los términos (con y sin acentos) que mapean a la forma canónica.

    Útil para construir índices de búsqueda multilingües (search_keywords).
    """
    target = strip_accents(canonical).strip().lower()
    aliases: set[str] = set()
    for alias, canon in SYNONYMS.items():
        if strip_accents(canon).strip().lower() == target:
            aliases.add(alias)
            aliases.add(strip_accents(alias))
        elif strip_accents(alias).strip().lower() == target:
            aliases.add(alias)
    return sorted(aliases, key=len, reverse=True)