"""add ai usage tracking tables

Revision ID: 1bea8a8b618f
Revises: a1b2c3d4e5f6
Create Date: 2026-09-26 12:12:57.683772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1bea8a8b618f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_logs_session_id'), 'ai_usage_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    op.create_table('user_daily_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_analyses_count', sa.Integer(), nullable=False),
    sa.Column('healthy_generations_count', sa.Integer(), nullable=False),
    sa.Column('total_ai_requests', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_daily_limits_date'), 'user_daily_limits', ['date'], unique=False)
    op.create_index(op.f('ix_user_daily_limits_session_id'), 'user_daily_limits', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_daily_limits_user_id'), 'user_daily_limits', ['user_id'], unique=False)
    op.create_index(op.f('ix_ingredients_normalized_name'), 'ingredients', ['normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredients_normalized_name'), table_name='ingredients')
    op.drop_index(op.f('ix_user_daily_limits_user_id'), table_name='user_daily_limits')
    op.drop_index(op.f('ix_user_daily_limits_session_id'), table_name='user_daily_limits')
    op.drop_index(op.f('ix_user_daily_limits_date'), table_name='user_daily_limits')
    op.drop_table('user_daily_limits')
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_session_id'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    # ### end Alembic commands ###
